server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.110.152.217:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
#消费者将去访问的微服务名称
server-url:
  nacos-user-service: http://nacos-payment-provider


feign:
  sentinel:
    enabled: true
