server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  #consul注册中心地址
  cloud:
    consul:
      host: 47.110.152.217
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false

